/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/kiwi/food_kiwi_01_4k.gltf -t -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function KiwiModel(props) {
  const { nodes, materials } = useGLTF("/kiwi/food_kiwi_01_4k.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.food_kiwi_01.geometry}
        material={materials.food_kiwi_01}
      />
    </group>
  );
}

useGLTF.preload("/kiwi/food_kiwi_01_4k.gltf");
